/*
Project Euler. Solution to Problem 2
( http://projecteuler.net/problem=2 )
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

gcc 002.c -time -o 002_c
*/
#include <stdio.h>

int main() {
	const int max = 4000000;
    int sum = 0;
	int i, j;

    for(i = 1, j = 1; i < max; i += j) {
        // check for even number
        if(i % 2 == 0) {

            // print plus sign before every number except the first one
            if (sum != 0)
                printf(" + ");

            printf("%d", i);
            sum += i;
        }

        // swapping two variables
        i -= j += i -= j = -j;
    }

    printf(" = %d\n", sum);
	return 0;
}
/*
Congratulations, the answer you gave to problem 2 is correct.
You are the 174268th person to have solved this problem.
Return to Problems page or go to thread 1 in the forum (http://projecteuler.net/thread=2).
*/

